# Site settings
title: Bitcrush Testing
email: contact@bitcrushtesting.com
description: > # this means to ignore newlines until "baseurl:"
  "Embedded Software Testing"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitcrushtesting.github.io" # the base hostname & protocol for your site
github_username: bitcrushtesting

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
